<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Design;

class DesignSeeder extends Seeder
{
    public function run()
    {
        $designs = [
            [
                'id' => 1,
                'design_code' => 'N001',
                'product_image_url' => '/images/products/Product-N001.webp',
                'design_url_1' => '/images/designs/N001-1.webp',
                'design_url_2' => '/images/designs/N001-2.webp',
                'color_code' => '#DAA520',
                'color_footer' => '#F3DBB5',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N001.webp',
            ],
            [
                'id' => 2,
                'design_code' => 'N002',
                'product_image_url' => '/images/products/Product-N002.webp',
                'design_url_1' => '/images/designs/N002-1.webp',
                'design_url_2' => '/images/designs/N002-2.webp',
                'color_code' => '#324B87',
                'color_footer' => '#7D9AAB',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N002.webp',
            ],
            [
                'id' => 3,
                'design_code' => 'N003',
                'product_image_url' => '/images/products/Product-N003.webp',
                'design_url_1' => '/images/designs/N003-1.webp',
                'design_url_2' => '/images/designs/N003-2.webp',
                'color_code' => '#9E5E26',
                'color_footer' => '#B27E2C',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N003.webp',
            ],
            [
                'id' => 4,
                'design_code' => 'N004',
                'product_image_url' => '/images/products/Product-N004.webp',
                'design_url_1' => '/images/designs/N004-1.webp',
                'design_url_2' => '/images/designs/N004-2.webp',
                'color_code' => '#CA2877',
                'color_footer' => '#DB5E9B',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N004.webp',
            ],
            [
                'id' => 5,
                'design_code' => 'N005',
                'product_image_url' => '/images/products/Product-N005.webp',
                'design_url_1' => '/images/designs/N005-1.webp',
                'design_url_2' => '/images/designs/N005-2.webp',
                'color_code' => '#5B967F',
                'color_footer' => '#91CCB5',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N005.webp',
            ],
            [
                'id' => 6,
                'design_code' => 'N006',
                'product_image_url' => '/images/products/Product-N006.webp',
                'design_url_1' => '/images/designs/N006-1.webp',
                'design_url_2' => '/images/designs/N006-2.webp',
                'color_code' => '#CC6579',
                'color_footer' => '#ED95A6',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N006.webp',
            ],
            [
                'id' => 7,
                'design_code' => 'N007',
                'product_image_url' => '/images/products/Product-N007.webp',
                'design_url_1' => '/images/designs/N007-1.webp',
                'design_url_2' => '/images/designs/N007-2.webp',
                'color_code' => '#FF004A',
                'color_footer' => '#F5648E',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N007.webp',
            ],
            [
                'id' => 8,
                'design_code' => 'N008',
                'product_image_url' => '/images/products/Product-N008.webp',
                'design_url_1' => '/images/designs/N008-1.webp',
                'design_url_2' => '/images/designs/N008-2.webp',
                'color_code' => '#15183A',
                'color_footer' => '4951AD',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N008.webp',
            ],
            [
                'id' => 9,
                'design_code' => 'N009',
                'product_image_url' => '/images/products/Product-N009.webp',
                'design_url_1' => '/images/designs/N009-1.webp',
                'design_url_2' => '/images/designs/N009-2.webp',
                'color_code' => '#435796',
                'color_footer' => '#667FD1',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N009.webp',
            ],
            [
                'id' => 10,
                'design_code' => 'N010',
                'product_image_url' => '/images/products/Product-N010.webp',
                'design_url_1' => '/images/designs/N010-1.webp',
                'design_url_2' => '/images/designs/N010-2.webp',
                'color_code' => '#638A65',
                'color_footer' => '#839B83',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N010.webp',
            ],
            [
                'id' => 11,
                'design_code' => 'N011',
                'product_image_url' => '/images/products/Product-N011.webp',
                'design_url_1' => '/images/designs/N011-1.webp',
                'design_url_2' => '/images/designs/N011-2.webp',
                'color_code' => '#B28A50',
                'color_footer' => '#D3B788',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N011.webp',
            ],
            [
                'id' => 12,
                'design_code' => 'N012',
                'product_image_url' => '/images/products/Product-N012.webp',
                'design_url_1' => '/images/designs/N012-1.webp',
                'design_url_2' => '/images/designs/N012-2.webp',
                'color_code' => '#655548',
                'color_footer' => '#7A695D',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N012.webp',
            ],
            [
                'id' => 13,
                'design_code' => 'N013',
                'product_image_url' => '/images/products/Product-N013.webp',
                'design_url_1' => '/images/designs/N013-1.webp',
                'design_url_2' => '/images/designs/N013-2.webp',
                'color_code' => '#9A2C52',
                'color_footer' => '#C96681',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N013.webp',
            ],
            [
                'id' => 14,
                'design_code' => 'N014',
                'product_image_url' => '/images/products/Product-N014.webp',
                'design_url_1' => '/images/designs/N014-1.webp',
                'design_url_2' => '/images/designs/N014-2.webp',
                'color_code' => '#D3414D',
                'color_footer' => '#F183A0',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N014.webp',
            ],
            [
                'id' => 15,
                'design_code' => 'N015',
                'product_image_url' => '/images/products/Product-N015.webp',
                'design_url_1' => '/images/designs/N015-1.webp',
                'design_url_2' => '/images/designs/N015-2.webp',
                'color_code' => '#AA5A6B',
                'color_footer' => '#D58385',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N015.webp',
            ],
            [
                'id' => 16,
                'design_code' => 'N016',
                'product_image_url' => '/images/products/Product-N016.webp',
                'design_url_1' => '/images/designs/N016-1.webp',
                'design_url_2' => '/images/designs/N016-2.webp',
                'color_code' => '#4B746A',
                'color_footer' => '#8EB5AB',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N016.webp',
            ],
            [
                'id' => 17,
                'design_code' => 'N017',
                'product_image_url' => '/images/products/Product-N017.webp',
                'design_url_1' => '/images/designs/N017-1.webp',
                'design_url_2' => '/images/designs/N017-2.webp',
                'color_code' => '#D16E29',
                'color_footer' => '#E1833B',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N017.webp',
            ],
            [
                'id' => 18,
                'design_code' => 'N018',
                'product_image_url' => '/images/products/Product-N018.webp',
                'design_url_1' => '/images/designs/N018-1.webp',
                'design_url_2' => '/images/designs/N018-2.webp',
                'color_code' => '#C9547C',
                'color_footer' => '#EAB2D3',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N018.webp',
            ],
            [
                'id' => 19,
                'design_code' => 'N019',
                'product_image_url' => '/images/products/Product-N019.webp',
                'design_url_1' => '/images/designs/N019-1.webp',
                'design_url_2' => '/images/designs/N019-2.webp',
                'color_code' => '#4A45A8',
                'color_footer' => '#6A67B7',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N019.webp',
            ],
            [
                'id' => 20,
                'design_code' => 'N020',
                'product_image_url' => '/images/products/Product-N020.webp',
                'design_url_1' => '/images/designs/N020-1.webp',
                'design_url_2' => '/images/designs/N020-2.webp',
                'color_code' => '#7F1418',
                'color_footer' => '#933A41',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N020.webp',
            ],
            [
                'id' => 21,
                'design_code' => 'N021',
                'product_image_url' => '/images/products/Product-N021.webp',
                'design_url_1' => '/images/designs/N021-1.webp',
                'design_url_2' => '/images/designs/N02i-2.webp',
                'color_code' => '#8B4871',
                'color_footer' => '#A66788',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N021.webp',
            ],
            [
                'id' => 22,
                'design_code' => 'N022',
                'product_image_url' => '/images/products/Product-N022.webp',
                'design_url_1' => '/images/designs/N022-1.webp',
                'design_url_2' => '/images/designs/N022-2.webp',
                'color_code' => '#BA4D39',
                'color_footer' => '#CE8953',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N022.webp',
            ],
            [
                'id' => 23,
                'design_code' => 'N023',
                'product_image_url' => '/images/products/Product-N023.webp',
                'design_url_1' => '/images/designs/N023-1.webp',
                'design_url_2' => '/images/designs/N023-2.webp',
                'color_code' => '#9A5425',
                'color_footer' => '#C48053',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N023.webp',
            ],
            [
                'id' => 24,
                'design_code' => 'N024',
                'product_image_url' => '/images/products/Product-N024.webp',
                'design_url_1' => '/images/designs/N024-1.webp',
                'design_url_2' => '/images/designs/N024-2.webp',
                'color_code' => '#C03C32',
                'color_footer' => '#ECA59D',
                'category' => 'floral',
                'thumbnail' => '/images/thumbnails/Thumb-N024.webp',
            ],
            [
                'id' => 25,
                'design_code' => 'N025',
                'product_image_url' => '/images/products/Product-N025.webp',
                'design_url_1' => '/images/designs/N025-1.webp',
                'design_url_2' => '/images/designs/N025-2.webp',
                'color_code' => '#613489',
                'color_footer' => '#715589',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N025.webp',
            ],
            [
                'id' => 26,
                'design_code' => 'N026',
                'product_image_url' => '/images/products/Product-N026.webp',
                'design_url_1' => '/images/designs/N026-1.webp',
                'design_url_2' => '/images/designs/N026-2.webp',
                'color_code' => '#435131',
                'color_footer' => '#B2C190',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N026.webp',
            ],
            [
                'id' => 27,
                'design_code' => 'N027',
                'product_image_url' => '/images/products/Product-N027.webp',
                'design_url_1' => '/images/designs/N027-1.webp',
                'design_url_2' => '/images/designs/N027-2.webp',
                'color_code' => '#2E6EB7',
                'color_footer' => '#6EB1E1',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N027.webp',
            ],
            [
                'id' => 28,
                'design_code' => 'N028',
                'product_image_url' => '/images/products/Product-N028.webp',
                'design_url_1' => '/images/designs/N028-1.webp',
                'design_url_2' => '/images/designs/N028-2.webp',
                'color_code' => '#913636',
                'color_footer' => '#ED9F9F',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N028.webp',
            ],
            [
                'id' => 29,
                'design_code' => 'N029',
                'product_image_url' => '/images/products/Product-N029.webp',
                'design_url_1' => '/images/designs/N029-1.webp',
                'design_url_2' => '/images/designs/N029-2.webp',
                'color_code' => '#AF6951',
                'color_footer' => '#D5967D',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N029.webp',
            ],
            [
                'id' => 30,
                'design_code' => 'N030',
                'product_image_url' => '/images/products/Product-N030.webp',
                'design_url_1' => '/images/designs/N030-1.webp',
                'design_url_2' => '/images/designs/N030-2.webp',
                'color_code' => '#AA2451',
                'color_footer' => '#E08FA7',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N030.webp',
            ],
            [
                'id' => 31,
                'design_code' => 'N031',
                'product_image_url' => '/images/products/Product-N031.webp',
                'design_url_1' => '/images/designs/N031-1.webp',
                'design_url_2' => '/images/designs/N031-2.webp',
                'color_code' => '#6B0C33',
                'color_footer' => '#895B70',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N031.webp',
            ],
            [
                'id' => 32,
                'design_code' => 'N032',
                'product_image_url' => '/images/products/Product-N032.webp',
                'design_url_1' => '/images/designs/N032-1.webp',
                'design_url_2' => '/images/designs/N032-2.webp',
                'color_code' => '#A5680F',
                'color_footer' => '#F4D39D',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N032.webp',
            ],
            [
                'id' => 33,
                'design_code' => 'N033',
                'product_image_url' => '/images/products/Product-N033.webp',
                'design_url_1' => '/images/designs/N033-1.webp',
                'design_url_2' => '/images/designs/N033-2.webp',
                'color_code' => '#1B6634',
                'color_footer' => '#4E825F',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N033.webp',
            ],
            [
                'id' => 34,
                'design_code' => 'N034',
                'product_image_url' => '/images/products/Product-N034.webp',
                'design_url_1' => '/images/designs/N034-1.webp',
                'design_url_2' => '/images/designs/N034-2.webp',
                'color_code' => '#351B68',
                'color_footer' => '#62537F',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N034.webp',
            ],
            [
                'id' => 35,
                'design_code' => 'N035',
                'product_image_url' => '/images/products/Product-N035.webp',
                'design_url_1' => '/images/designs/N035-1.webp',
                'design_url_2' => '/images/designs/N035-2.webp',
                'color_code' => '#9B34A3',
                'color_footer' => '#BA79BF',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N035.webp',
            ],
            [
                'id' => 36,
                'design_code' => 'N036',
                'product_image_url' => '/images/products/Product-N036.webp',
                'design_url_1' => '/images/designs/N036-1.webp',
                'design_url_2' => '/images/designs/N036-2.webp',
                'color_code' => '#DD743A',
                'color_footer' => '#EDA983',
                'category' => 'abstract',
                'thumbnail' => '/images/thumbnails/Thumb-N036.webp',
            ],
            [
                'id' => 49,
                'design_code' => 'N049',
                'product_image_url' => '/images/products/Product-N049.webp',
                'design_url_1' => '/images/designs/N049-1.webp',
                'design_url_2' => '/images/designs/N049-2.webp',
                'color_code' => '#4F5D83',
                'color_footer' => '#A1AAC2',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N049.webp',
            ],
            [
                'id' => 50,
                'design_code' => 'N050',
                'product_image_url' => '/images/products/Product-N050.webp',
                'design_url_1' => '/images/designs/N050-1.webp',
                'design_url_2' => '/images/designs/N050-2.webp',
                'color_code' => '#EA9632',
                'color_footer' => '#F2AF5F',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N050.webp',
            ],
            [
                'id' => 51,
                'design_code' => 'N051',
                'product_image_url' => '/images/products/Product-N051.webp',
                'design_url_1' => '/images/designs/N051-1.webp',
                'design_url_2' => '/images/designs/N051-2.webp',
                'color_code' => '#7F5230',
                'color_footer' => '#C6804B',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N051.webp',
            ],
            [
                'id' => 52,
                'design_code' => 'N052',
                'product_image_url' => '/images/products/Product-N052.webp',
                'design_url_1' => '/images/designs/N052-1.webp',
                'design_url_2' => '/images/designs/N052-2.webp',
                'color_code' => '#9B2C27',
                'color_footer' => '#AA514D',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N052.webp',
            ],
            [
                'id' => 53,
                'design_code' => 'N053',
                'product_image_url' => '/images/products/Product-N053.webp',
                'design_url_1' => '/images/designs/N053-1.webp',
                'design_url_2' => '/images/designs/N053-2.webp',
                'color_code' => '#A05A2A',
                'color_footer' => '#C48C66',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N053.webp',
                'primary_text_color' => '#C49A7A',
            ],
            [
                'id' => 54,
                'design_code' => 'N054',
                'product_image_url' => '/images/products/Product-N054.webp',
                'design_url_1' => '/images/designs/N054-1.webp',
                'design_url_2' => '/images/designs/N054-2.webp',
                'color_code' => '#826127',
                'color_footer' => '#A58C5E',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N054.webp',
            ],
            [
                'id' => 55,
                'design_code' => 'N055',
                'product_image_url' => '/images/products/Product-N055.webp',
                'design_url_1' => '/images/designs/N055-1.webp',
                'design_url_2' => '/images/designs/N055-2.webp',
                'color_code' => '#374460',
                'color_footer' => '#5C6272',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N055.webp',
            ],
            [
                'id' => 56,
                'design_code' => 'N056',
                'product_image_url' => '/images/products/Product-N056.webp',
                'design_url_1' => '/images/designs/N056-1.webp',
                'design_url_2' => '/images/designs/N056-2.webp',
                'color_code' => '#F47199',
                'color_footer' => '#F2ADC3',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N056.webp',
            ],
            [
                'id' => 57,
                'design_code' => 'N057',
                'product_image_url' => '/images/products/Product-N057.webp',
                'design_url_1' => '/images/designs/N057-1.webp',
                'design_url_2' => '/images/designs/N057-2.webp',
                'color_code' => '#604C40',
                'color_footer' => '#7D7068',
                'category' => 'minimalist',
                'thumbnail' => '/images/thumbnails/Thumb-N057.webp',
            ],

            // Add more entries as needed
        ];

        foreach ($designs as $design) {
            Design::create($design);
        }
    }
}
